package com.metaforge.graph.application.service;

import com.metaforge.graph.api.dto.CreateDraftRequest;
import com.metaforge.graph.api.dto.RelationInstanceDraftDto;
import com.metaforge.graph.api.service.RelationActivationService;
import com.metaforge.graph.api.service.RelationDraftService;
import com.metaforge.graph.domain.model.aggregate.RelationInstance;
import com.metaforge.graph.domain.repository.RelationInstanceRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;

/**
 * 关系实例自动构建服务。
 *
 * <p>封装实体变更后的关联引用解析、增量对比、批量关系生成/更新/销毁逻辑。
 * 遵循最终一致性语义——每条关系的生成与生效在独立事务内执行。
 */
@Service
@Transactional
public class RelationAutoBuildService {

    private static final Logger log = LoggerFactory.getLogger(RelationAutoBuildService.class);

    private final RelationDraftService draftService;
    private final RelationActivationService activationService;
    private final RelationInstanceRepository instanceRepository;

    public RelationAutoBuildService(RelationDraftService draftService,
                                     RelationActivationService activationService,
                                     RelationInstanceRepository instanceRepository) {
        this.draftService = draftService;
        this.activationService = activationService;
        this.instanceRepository = instanceRepository;
    }

    /**
     * 实体生效时：解析实体关联引用字段，生成并自动生效关系实例。
     *
     * @param entityFqn    实体 FQN
     * @param relationTypeFqn 关系类型 FQN
     * @param targetEntityFqn 目标实体 FQN
     * @param relationName  关系名称
     */
    public void buildRelationOnActivate(String entityFqn, String relationTypeFqn,
                                         String targetEntityFqn, String relationName) {
        log.info("自动构建关系: source={}, type={}, target={}", entityFqn, relationTypeFqn, targetEntityFqn);

        try {
            CreateDraftRequest request = new CreateDraftRequest();
            request.setSourceEntityFqn(entityFqn);
            request.setRelationTypeFqn(relationTypeFqn);
            request.setTargetEntityFqn(targetEntityFqn);
            request.setName(relationName);

            Map<String, Object> content = new HashMap<>();
            content.put("autoGenerated", true);
            request.setContent(content);

            RelationInstanceDraftDto draft = draftService.createDraft(request);
            activationService.activate(draft.getFqn());

            log.info("自动构建并生效成功: fqn={}", draft.getFqn());
        } catch (Exception e) {
            log.warn("自动构建关系跳过（可能已存在）: source={}, target={}, reason={}",
                    entityFqn, targetEntityFqn, e.getMessage());
        }
    }

    /**
     * 实体下线时：下线该实体作为源端/目标端的所有生效关系。
     *
     * @param entityFqn 实体 FQN
     */
    public void deprecateRelationsOnEntityDeprecate(String entityFqn) {
        log.info("自动下线关联关系: entity={}", entityFqn);

        List<RelationInstance> outbound = instanceRepository.findBySourceEntityFqn(entityFqn);
        List<RelationInstance> inbound = instanceRepository.findByTargetEntityFqn(entityFqn);

        for (RelationInstance rel : outbound) {
            try {
                activationService.deprecate(rel.getFqnValue());
            } catch (Exception e) {
                log.warn("自动下线出边关系失败: fqn={}, reason={}", rel.getFqnValue(), e.getMessage());
            }
        }

        for (RelationInstance rel : inbound) {
            try {
                activationService.deprecate(rel.getFqnValue());
            } catch (Exception e) {
                log.warn("自动下线入边关系失败: fqn={}, reason={}", rel.getFqnValue(), e.getMessage());
            }
        }

        log.info("自动下线关联关系完成: entity={}, outbound={}, inbound={}",
                entityFqn, outbound.size(), inbound.size());
    }
}
